# Generated by Django 4.1.4 on 2022-12-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_taskpriority_taskstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('ALTA', 'ALTA'), ('MEDIA', 'MEDIA'), ('BAJA', 'BAJA')], max_length=10, null=True)),
                ('priority', models.CharField(blank=True, choices=[('BACKLOG', 'BACKLOG'), ('TO DO', 'TO DO'), ('DOING', 'DOING'), ('TEST', 'TEST'), ('DONE', 'DONE')], max_length=10, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TaskPriority',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.requesttask'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
